# **Data Cleaning**

## **Data Reviewing**

In [74]:
import pandas as pd

In [75]:
magang_opportunities = pd.read_csv('magang_opportunities.csv')

magang_opportunities.head()

,meta,id,name,description,mitra_id,start_period,months_duration,activity_type,location,fields_of_study,...,show_salary,mobilization,accommodation,is_applied,wishlist,is_external,external_platform_name,external_platform_logo_url,mitra_name,salary
0,NaN,b794e1a1-ecd6-449d-9ed9-0118a2e02626,Website Developer,<p><strong>Kualifikasi :</strong>&nbsp;</p><ul...,c7746ff1-87de-47bb-a43f-6d63f521e07c,2024-03-01T00:00:00+07:00,3,WFH,Kota Surabaya,[],...,False,False,False,False,False,False,NaN,NaN,CV. APPAREL BERKAH SELALU,NaN
1,NaN,7c8623ef-5f9b-470d-bc7a-73b1dd706c8b,Software Architect Intern,<p>To help architect team on demonstration of ...,af00bd20-3ac2-44a4-877f-af4307f9b599,2024-03-01T00:00:00+07:00,6,WFO,Kota Jakarta Selatan,['Teknik Informatika dan Ilmu Komputer'],...,False,False,False,False,False,False,NaN,NaN,PT. Idemia Technologies Indonesia,NaN
2,NaN,bd95c730-b157-4fc5-8791-9dc9ea5e0e32,Product Marketing Intern,<p>- Design and develop sharepoint page to sup...,af00bd20-3ac2-44a4-877f-af4307f9b599,2024-03-01T00:00:00+07:00,6,WFO,Kota Jakarta Selatan,['Teknik Informatika dan Ilmu Komputer'],...,False,False,False,False,False,False,NaN,NaN,PT. Idemia Technologies Indonesia,NaN
3,NaN,fc01895c-0d74-4874-a8f2-d1d46956d697,Asisten Finance,<ol><li>Pemahaman Sistem Keuangan Sekolah: And...,0bf5a4d1-9980-48ae-ad65-48e3b239f15c,2024-03-01T00:00:00+07:00,4,WFO,Kota Banda Aceh,[],...,False,False,False,False,False,False,NaN,NaN,SMAN 14 Banda Aceh,NaN
4,NaN,b6062e51-4764-474c-a2b7-617affd56959,Marketing Asuransi Mini Mikro,<p>WFH dari Seluruh Indonesia.</p><p><br></p><...,6bbc729e-c3ee-46a1-93be-2b9f3b5f478d,2024-03-01T00:00:00+07:00,4,WFH,Kota Banda Aceh,[],...,False,False,False,False,False,False,NaN,NaN,Natural Aceh,NaN

In [76]:
data = pd.DataFrame({
  'id': list(magang_opportunities['id'].values),
  'name': list(magang_opportunities['name'].values),
  'description': list(magang_opportunities['description'].values),
  'skills': list(magang_opportunities['skills'].values)
})

data

,id,name,description,skills
0,b794e1a1-ecd6-449d-9ed9-0118a2e02626,Website Developer,<p><strong>Kualifikasi :</strong>&nbsp;</p><ul...,"['Komunikasi', 'Kreatif', 'Pemahaman Industri'..."
1,7c8623ef-5f9b-470d-bc7a-73b1dd706c8b,Software Architect Intern,<p>To help architect team on demonstration of ...,"['Komunikasi', 'Kreatif', 'Desain Grafis', 'Co..."
2,bd95c730-b157-4fc5-8791-9dc9ea5e0e32,Product Marketing Intern,<p>- Design and develop sharepoint page to sup...,"['Kreatif', 'Analisis Data', 'Pemahaman Lingku..."
3,fc01895c-0d74-4874-a8f2-d1d46956d697,Asisten Finance,<ol><li>Pemahaman Sistem Keuangan Sekolah: And...,"['Administrasi', 'Operasional', 'Komunikasi', ..."
4,b6062e51-4764-474c-a2b7-617affd56959,Marketing Asuransi Mini Mikro,<p>WFH dari Seluruh Indonesia.</p><p><br></p><...,"['Operasional', 'Kreatif', 'Administrasi', 'Ko..."
...,...,...,...,...
677,7a2f6ef1-844d-4c70-99bc-03be7d5aac88,Marketing Creative Intern,Responsibilities \n\nSupport Marketing and Bra...,NaN
678,404ccd37-0c1e-43ab-bdfd-7b9a6fee551c,Graphic Design (Intern),Kami Idea merupakan sebuah usaha atau bisnis y...,NaN
679,5a704786-6865-40c9-9086-a2bd85dc5098,Influencer Management Intern,- Last semester student from reputable univers...,NaN
680,780902fd-e51a-463c-a012-e7a0941da47e,New Business Development Internship (Jakarta U...,- Final year student or fresh graduate \n- Pas...,NaN
681,1d00c1ea-95ee-4d24-b5be-63c3ff276bd1,Finance & Accounting Intern,"Kualifikasi :\n- Mahasiwa aktif, dan freshgrad...",NaN

## **Combine Text**

In [81]:
import ast

In [82]:
# Convert the "skills" column from string to list for non-null values
data['skills'] = data['skills'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else x)

# Join the skills into a single string
data['skills'] = data['skills'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)

# Combine "name," "description," and "skills" into a new column
data['combined_text'] = data['name'] + ' ' + data['description'] + ' ' + data['skills'].astype(str)

data['combined_text']

0      Website Developer <p><strong>Kualifikasi :</st...
1      Software Architect Intern <p>To help architect...
2      Product Marketing Intern <p>- Design and devel...
3      Asisten Finance <ol><li>Pemahaman Sistem Keuan...
4      Marketing Asuransi Mini Mikro  <p>WFH dari Sel...
                             ...
677    Marketing Creative Intern Responsibilities \n\...
678    Graphic Design (Intern) Kami Idea merupakan se...
679    Influencer Management Intern - Last semester s...
680    New Business Development Internship (Jakarta U...
681    Finance & Accounting Intern Kualifikasi :\n- M...
Name: combined_text, Length: 682, dtype: object

## **Case Folding**

In [88]:
data['result_case_folding_data'] = data['combined_text'].apply(lambda x: x.casefold())
data['result_case_folding_data']

0      website developer <p><strong>kualifikasi :</st...
1      software architect intern <p>to help architect...
2      product marketing intern <p>- design and devel...
3      asisten finance <ol><li>pemahaman sistem keuan...
4      marketing asuransi mini mikro  <p>wfh dari sel...
                             ...
677    marketing creative intern responsibilities \n\...
678    graphic design (intern) kami idea merupakan se...
679    influencer management intern - last semester s...
680    new business development internship (jakarta u...
681    finance & accounting intern kualifikasi :\n- m...
Name: result_case_folding_data, Length: 682, dtype: object

## **Remove Html Tags**

In [89]:
from lxml import etree

In [94]:
def remove_html_tags(text):
    parser = etree.HTMLParser()
    tree = etree.fromstring(text, parser)
    return etree.tostring(tree, encoding='unicode', method='text')

def remove_newlines(text):
    return text.replace('\n', ' ').replace('\r', '').replace('\t', '').strip()

data['result_remove_html_tags'] = data['result_case_folding_data'].apply(remove_html_tags).apply(remove_newlines)
data[['id','result_remove_html_tags']]

,id,result_remove_html_tags
0,b794e1a1-ecd6-449d-9ed9-0118a2e02626,website developer kualifikasi :Â wajib memiliki...
1,7c8623ef-5f9b-470d-bc7a-73b1dd706c8b,software architect intern to help architect te...
2,bd95c730-b157-4fc5-8791-9dc9ea5e0e32,product marketing intern - design and develop ...
3,fc01895c-0d74-4874-a8f2-d1d46956d697,asisten finance pemahaman sistem keuangan seko...
4,b6062e51-4764-474c-a2b7-617affd56959,marketing asuransi mini mikro wfh dari seluru...
...,...,...
677,7a2f6ef1-844d-4c70-99bc-03be7d5aac88,marketing creative intern responsibilities s...
678,404ccd37-0c1e-43ab-bdfd-7b9a6fee551c,graphic design (intern) kami idea merupakan se...
679,5a704786-6865-40c9-9086-a2bd85dc5098,influencer management intern - last semester s...
680,780902fd-e51a-463c-a012-e7a0941da47e,new business development internship (jakarta u...
681,1d00c1ea-95ee-4d24-b5be-63c3ff276bd1,finance & accounting intern kualifikasi : - ma...

## **Case Folding**

In [19]:
data.apply(lambda x: x.casefold() if x.dtype == object else x)

data

AttributeError: 'Series' object has no attribute 'casefold'